### PR TITLE
Update ci config

### PR DESCRIPTION
**Pull request by nihonjinrxs**
This PR updates the CI config to do the following:
- Run CI on `master` branch at least once daily via cron
- Run CI on each push to any branch on the repo
- Run CI on each pull request against `master` branch
- Check TypeScript types (`npm run check-typings`) on each CI run
- Run the linter (`npm run lint`) on each CI run

It also updates the CI information in the contributing docs to reflect this new setup on Github Actions.

Turning on linting as part of CI identified a few lint failures (single quote for strings) in the test files, so I've fixed those as well.

Closing #56 in favor of this one.

### CODE REVIEW

**Comment by nihonjinrxs** [comment]
I've rebased this branch to move the lint fixes and docs generation to the end, so as to make for easier reviewing. Hope that helps.

**Comment by nihonjinrxs** [comment]
@bog when you get a chance, I'd appreciate a quick review on this one.

**Review by bog — APPROVED** [review]
Looks good. Makes me realize we should just jump in now to switch to `main` instead of `master`.

**Comment by nihonjinrxs** [comment]
Sounds good. Will do.

**Pull request merged**
